// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcI5SurZJF9jDVre70eIU40GLQhauaYco',
    appId: '1:709498068085:android:bf43812a002104f0446c3c',
    messagingSenderId: '709498068085',
    projectId: 'sharp-effort-299723',
    databaseURL: 'https://sharp-effort-299723-default-rtdb.firebaseio.com',
    storageBucket: 'sharp-effort-299723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvw7Ddh-FGhIGWgneGAvqcN8Ek0qW7z5w',
    appId: '1:709498068085:ios:c304fec6f4933904446c3c',
    messagingSenderId: '709498068085',
    projectId: 'sharp-effort-299723',
    databaseURL: 'https://sharp-effort-299723-default-rtdb.firebaseio.com',
    storageBucket: 'sharp-effort-299723.appspot.com',
    iosClientId: '709498068085-1vqhaj5hnvk6uulojs2jrij38gllvsbj.apps.googleusercontent.com',
    iosBundleId: 'com.palBazar.app',
  );
}
